spring.application.name=airBnb

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



#docker run --name airbnb-postgres \
#  -e POSTGRES_DB=airbnb \
#  -e POSTGRES_USER=postgres \
#  -e POSTGRES_PASSWORD=postgres \
#  -p 5432:5432 \
#  -d postgres:latest


#docker start airbnb-postgres
